import type { MathCategoryId } from './types';

export type MathCategoryConfig = {
  id: MathCategoryId;
  label: string;
  supportedActions: string[];
  practicePrompt: string;
  examples: Array<{ expr: string; desc: string }>;
};

export const MATH_CATEGORY_ORDER: MathCategoryId[] = [
  'algebra',
  'geometry',
  'calculus',
  'trigonometry',
  'sequences-series',
  'linear-algebra',
  'statistics',
  'vectors',
  'matrices',
  'differential-equations',
  'discrete',
  'physics',
];

export const MATH_CATEGORIES: Record<MathCategoryId, MathCategoryConfig> = {
  algebra: {
    id: 'algebra',
    label: 'Algebra',
    supportedActions: [
      'Solve linear equation',
      'Quadratic roots',
      'Systems of equations',
      'Inequalities',
      'Simplify expression',
      'Factor / expand',
      'Completing the square',
      'Logarithm equations',
      'Exponential equations',
      'Rational expressions',
    ],
    practicePrompt: 'Create algebra practice with a linear equation, a quadratic, a system, an inequality, and one harder logarithm or exponential extension question. Show full working.',
    examples: [
      { expr: '2x + 5 = 11',                        desc: 'Solve a linear equation' },
      { expr: '2x + 5 <= 11',                        desc: 'Solve a linear inequality' },
      { expr: 'x^2 - 5x + 6 = 0',                   desc: 'Solve a quadratic equation' },
      { expr: 'factor x^2 - 5x + 6',                desc: 'Factor a quadratic expression' },
      { expr: 'expand (x + 3)(x - 1)',               desc: 'Expand double brackets' },
      { expr: 'simplify (x^2 - 4) / (x - 2)',       desc: 'Simplify a rational expression' },
      { expr: 'system x + y = 3; x - y = 1',        desc: 'Solve simultaneous equations' },
      { expr: 'system 2x + y = 8; x - y = 1',       desc: 'Another simultaneous system' },
      { expr: 'x^2 + 6x + 5 = 0',                   desc: 'Complete the square to solve' },
      { expr: 'log(x) = 2',                          desc: 'Solve a logarithm equation' },
      { expr: '2^x = 16',                            desc: 'Solve an exponential equation' },
      { expr: '3x^2 + 2x - 1 = 0',                  desc: 'Quadratic with non-unit leading term' },
    ],
  },

  geometry: {
    id: 'geometry',
    label: 'Geometry',
    supportedActions: [
      'Pythagorean theorem',
      'Distance between points',
      'Midpoint of a segment',
      'Line through two points',
      'Circle equation',
      'Triangle area (sides)',
      'Triangle area (base & height)',
      'Rectangle area & perimeter',
      'Circle area & circumference',
      'Sphere volume & surface area',
      'Cylinder volume',
      'Cone volume',
      'Sector area',
    ],
    practicePrompt: 'Create geometry practice with coordinate geometry, a circle problem, a volume or surface-area problem, and one applied measurement question. Show full working.',
    examples: [
      { expr: 'hypotenuse 3 4',                               desc: 'Pythagorean theorem — find hypotenuse' },
      { expr: 'distance (0,0) (3,4)',                         desc: 'Distance between two points' },
      { expr: 'midpoint of (0,0) and (6,4)',                  desc: 'Midpoint of a segment' },
      { expr: 'line through (1,2) and (4,6)',                 desc: 'Equation of a line from two points' },
      { expr: 'equation of circle: center (2,-3), radius 5', desc: 'Standard circle equation' },
      { expr: 'area of triangle with sides 3, 4, 5',         desc: "Triangle area via Heron's formula" },
      { expr: 'area of triangle base 8 height 5',            desc: 'Triangle area — base and height' },
      { expr: 'area of rectangle 6 9',                        desc: 'Rectangle area' },
      { expr: 'perimeter of rectangle 6 9',                   desc: 'Rectangle perimeter' },
      { expr: 'area of circle radius 7',                      desc: 'Circle area' },
      { expr: 'circumference of circle radius 7',             desc: 'Circle circumference' },
      { expr: 'volume of sphere with radius 7',               desc: 'Sphere volume' },
      { expr: 'surface area of sphere radius 4',              desc: 'Sphere surface area' },
      { expr: 'volume of cylinder radius 3 height 10',        desc: 'Cylinder volume' },
      { expr: 'volume of cone radius 4 height 9',             desc: 'Cone volume' },
      { expr: 'sector area radius 6 angle 60',                desc: 'Sector area (degrees)' },
    ],
  },

  calculus: {
    id: 'calculus',
    label: 'Calculus',
    supportedActions: [
      'Derivative',
      'Second derivative',
      'Chain rule',
      'Product rule',
      'Quotient rule',
      'Indefinite integral',
      'Definite integral',
      'Limit',
      'L\'Hopital\'s rule',
    ],
    practicePrompt: 'Create calculus practice with a derivative (polynomial), a chain-rule problem, a definite integral, a limit, and one harder conceptual check. Show full working.',
    examples: [
      { expr: 'derivative of x^3',                      desc: 'Differentiate a power function' },
      { expr: 'derivative of x^2 + 2x + 1',             desc: 'Differentiate a polynomial' },
      { expr: 'derivative of sin(x)',                    desc: 'Differentiate a trig function' },
      { expr: 'derivative of sin(x^2)',                  desc: 'Chain rule — composite function' },
      { expr: 'derivative of x*sin(x)',                  desc: 'Product rule example' },
      { expr: 'derivative of sin(x)/x',                  desc: 'Quotient rule example' },
      { expr: 'derivative of e^x',                       desc: 'Derivative of exponential' },
      { expr: 'derivative of log(x)',                    desc: 'Derivative of natural log' },
      { expr: 'integral of sin(x) dx',                   desc: 'Find an antiderivative' },
      { expr: 'integral of x^2 dx',                      desc: 'Power rule in reverse' },
      { expr: 'integral of e^x dx',                      desc: 'Integrate the exponential' },
      { expr: 'integral from 0 to pi of sin(x) dx',     desc: 'Evaluate a definite integral' },
      { expr: 'integral from 0 to 1 of x^2 dx',         desc: 'Definite integral — power' },
      { expr: 'limit x->0 of sin(x)/x',                 desc: 'Classic limit (L\'Hopital)' },
      { expr: 'limit x->2 of (x^2 - 4)/(x - 2)',       desc: 'Factoring to resolve a limit' },
      { expr: 'limit x->inf of 1/x',                    desc: 'Limit at infinity' },
    ],
  },

  trigonometry: {
    id: 'trigonometry',
    label: 'Trigonometry',
    supportedActions: [
      'Exact trig values',
      'Inverse trig (arcsin / arccos / arctan)',
      'Trig identities',
      'Law of sines',
      'Law of cosines',
      'Degrees to radians',
      'Radians to degrees',
      'Amplitude & period',
    ],
    practicePrompt: 'Create trigonometry practice with exact values, an identity check, an inverse trig problem, and one applied triangle problem using the law of sines or cosines.',
    examples: [
      { expr: 'sin(pi/6)',                              desc: 'Exact value — sin 30\u00b0' },
      { expr: 'cos(pi/3)',                              desc: 'Exact value — cos 60\u00b0' },
      { expr: 'tan(pi/4)',                              desc: 'Exact value — tan 45\u00b0' },
      { expr: 'sin(pi/4)',                              desc: 'Exact value — sin 45\u00b0' },
      { expr: 'cos(pi/6)',                              desc: 'Exact value — cos 30\u00b0' },
      { expr: 'tan(pi/3)',                              desc: 'Exact value — tan 60\u00b0' },
      { expr: 'sin(pi/6)^2 + cos(pi/6)^2',            desc: 'Verify the Pythagorean identity' },
      { expr: 'sin(pi/3)^2 + cos(pi/3)^2',            desc: 'Identity check at 60\u00b0' },
      { expr: 'asin(0.5)',                              desc: 'Inverse sine (arcsin)' },
      { expr: 'acos(0.5)',                              desc: 'Inverse cosine (arccos)' },
      { expr: 'atan(1)',                                desc: 'Inverse tangent (arctan)' },
      { expr: 'degrees to radians 45',                 desc: 'Convert 45\u00b0 to radians' },
      { expr: 'radians to degrees pi/3',               desc: 'Convert \u03c0/3 to degrees' },
    ],
  },

  'sequences-series': {
    id: 'sequences-series',
    label: 'Sequences & Series',
    supportedActions: [
      'Arithmetic \u2014 nth term',
      'Arithmetic \u2014 sum to n',
      'Geometric \u2014 nth term',
      'Geometric \u2014 sum to n',
      'Geometric \u2014 sum to infinity',
      'Identify sequence type',
    ],
    practicePrompt: 'Create sequences and series practice with an arithmetic nth term, a geometric sum, a sum-to-infinity question, and one interpretation question. Show full working.',
    examples: [
      { expr: 'arithmetic nth 3 2 10',   desc: '10th term of arithmetic seq (a=3, d=2)' },
      { expr: 'arithmetic sum 3 2 10',   desc: 'Sum of first 10 arithmetic terms' },
      { expr: 'arithmetic nth 5 3 20',   desc: '20th term (a=5, d=3)' },
      { expr: 'arithmetic sum 1 4 15',   desc: 'Sum of first 15 terms (a=1, d=4)' },
      { expr: 'geometric nth 2 3 5',     desc: '5th term of geometric seq (a=2, r=3)' },
      { expr: 'geometric sum 2 3 5',     desc: 'Sum of first 5 geometric terms' },
      { expr: 'geometric nth 1 0.5 8',   desc: 'Geometric seq with fraction ratio' },
      { expr: 'geometric sum 4 0.5 10',  desc: 'Sum of 10 terms (r = 0.5)' },
    ],
  },

  'linear-algebra': {
    id: 'linear-algebra',
    label: 'Linear Algebra',
    supportedActions: [
      'Matrix multiplication',
      'Determinant',
      'Matrix inverse',
      'Transpose',
      'Row echelon form',
      'Eigenvalue check',
      'Identity matrix',
    ],
    practicePrompt: 'Create linear algebra practice with a 2x2 multiplication, a determinant, an inverse, and one interpretation question about what the result means geometrically.',
    examples: [
      { expr: '[[1,2],[3,4]] * [[2,0],[1,2]]',    desc: '2\u00d72 matrix multiplication' },
      { expr: '[[2,1],[0,3]] * [[1,0],[2,1]]',    desc: 'Another matrix product' },
      { expr: 'det([[2,3],[1,4]])',                desc: '2\u00d72 determinant' },
      { expr: 'det([[1,2,3],[4,5,6],[7,8,9]])',   desc: '3\u00d73 determinant' },
      { expr: 'inv([[1,2],[3,5]])',                desc: 'Matrix inverse (2\u00d72)' },
      { expr: 'inv([[2,1],[1,1]])',                desc: 'Another matrix inverse' },
      { expr: '[[1,2],[3,4]] * [[1,0],[0,1]]',    desc: 'Multiply by the identity matrix' },
    ],
  },

  statistics: {
    id: 'statistics',
    label: 'Statistics',
    supportedActions: [
      'Mean',
      'Median',
      'Mode',
      'Range',
      'Variance',
      'Standard deviation',
      'Combinations C(n,r)',
      'Permutations P(n,r)',
    ],
    practicePrompt: 'Create statistics practice from a small dataset: compute mean, median, mode, range, variance, and standard deviation, then one combinatorics question. Show all working.',
    examples: [
      { expr: 'mean([4, 7, 13, 2, 8])',          desc: 'Compute the mean' },
      { expr: 'mean([10, 20, 30, 40, 50])',       desc: 'Mean of an arithmetic dataset' },
      { expr: 'median([4, 7, 13, 2, 8])',         desc: 'Find the median' },
      { expr: 'median([3, 1, 4, 1, 5, 9, 2, 6])', desc: 'Median of an 8-value list' },
      { expr: 'std([4, 7, 13, 2, 8])',            desc: 'Standard deviation' },
      { expr: 'variance([4, 7, 13, 2, 8])',        desc: 'Variance of a dataset' },
      { expr: 'combinations(5, 2)',               desc: 'C(5,2) \u2014 count combinations' },
      { expr: 'combinations(10, 3)',              desc: 'C(10,3)' },
      { expr: 'permutations(5, 2)',               desc: 'P(5,2) \u2014 ordered arrangements' },
      { expr: 'permutations(6, 3)',               desc: 'P(6,3)' },
    ],
  },

  vectors: {
    id: 'vectors',
    label: 'Vectors',
    supportedActions: [
      'Dot product',
      'Magnitude',
      'Angle between vectors',
      'Unit vector',
      'Vector addition',
      'Scalar multiplication',
      'Cross product (3D)',
    ],
    practicePrompt: 'Create vector questions using dot product, magnitude, angle, unit vectors, and cross product where appropriate. Include geometric interpretation.',
    examples: [
      { expr: 'dot product [3,2] [1,4]',          desc: 'Dot product of two 2D vectors' },
      { expr: 'dot product [1,2,3] [4,5,6]',      desc: 'Dot product of two 3D vectors' },
      { expr: 'magnitude [3,4]',                  desc: 'Magnitude of a 2D vector' },
      { expr: 'magnitude [1,2,2]',                desc: 'Magnitude of a 3D vector' },
      { expr: 'angle between [1,0] [0,1]',        desc: 'Angle between perpendicular vectors' },
      { expr: 'angle between [3,4] [1,2]',        desc: 'Angle between two 2D vectors' },
      { expr: 'dot product [2,0] [0,3]',          desc: 'Dot product of orthogonal vectors' },
    ],
  },

  matrices: {
    id: 'matrices',
    label: 'Matrices',
    supportedActions: [
      'Multiply',
      'Determinant',
      'Inverse',
      'Add / subtract',
      'Scalar multiply',
      'Transpose',
    ],
    practicePrompt: 'Create matrix practice with multiplication, determinant, inverse, and one scalar or addition problem. Mirror exam-style computation and interpretation.',
    examples: [
      { expr: '[[1,2],[3,4]] * [[5,6],[7,8]]',    desc: 'Multiply two 2\u00d72 matrices' },
      { expr: '[[2,1,0],[1,3,1],[0,1,2]] * [[1],[2],[3]]', desc: 'Matrix-vector product (3\u00d73 \u00d7 3\u00d71)' },
      { expr: 'det([[1,2],[3,4]])',                desc: '2\u00d72 determinant' },
      { expr: 'det([[2,1,0],[1,2,1],[0,1,2]])',   desc: '3\u00d73 determinant' },
      { expr: 'inv([[2,1],[1,1]])',                desc: 'Matrix inverse \u2014 check A\u00b7A\u207b\u00b9 = I' },
      { expr: 'inv([[3,1],[5,2]])',                desc: 'Another 2\u00d72 inverse' },
    ],
  },

  'differential-equations': {
    id: 'differential-equations',
    label: 'Differential Equations',
    supportedActions: [
      '1st-order linear ODE',
      '1st-order separable',
      'Direct integration',
      'Exponential growth/decay',
      '2nd-order homogeneous',
      '2nd-order with constant forcing',
      'Characteristic equation',
    ],
    practicePrompt: 'Create differential equations practice with a first-order ODE, an exponential decay model, a second-order homogeneous ODE, and one characteristic-equation problem. Show full working.',
    examples: [
      { expr: "y' = -2y",                desc: 'Exponential decay (first-order)' },
      { expr: "y' + 2y = 4",             desc: 'First-order linear ODE' },
      { expr: "y' = 3x^2",               desc: 'Direct integration' },
      { expr: "y' = y",                  desc: 'Exponential growth model' },
      { expr: "y'' + 3y' + 2y = 0",     desc: '2nd-order homogeneous ODE' },
      { expr: "y'' + y = 0",             desc: 'Pure oscillator (SHM)' },
      { expr: "y'' - 4y = 0",            desc: 'Real characteristic roots' },
      { expr: "y'' + 4y = 0",            desc: 'Complex roots \u2014 oscillatory solution' },
    ],
  },

  discrete: {
    id: 'discrete',
    label: 'Discrete Math',
    supportedActions: [
      'GCD',
      'LCM',
      'Combinations C(n,r)',
      'Permutations P(n,r)',
      'Fibonacci',
      'Modular arithmetic',
      'Prime factorisation',
      'Floor / ceiling',
    ],
    practicePrompt: 'Create discrete mathematics practice covering GCD/LCM, combinatorics, Fibonacci, modular arithmetic, and prime factorisation. Include worked solutions.',
    examples: [
      { expr: 'gcd(48, 36)',       desc: 'Greatest common divisor' },
      { expr: 'gcd(120, 45)',      desc: 'GCD with Euclid\u2019s algorithm' },
      { expr: 'lcm(12, 18)',       desc: 'Least common multiple' },
      { expr: 'lcm(6, 14)',        desc: 'LCM of two numbers' },
      { expr: 'C(10, 3)',          desc: 'Combinations C(10,3)' },
      { expr: 'C(7, 2)',           desc: 'Combinations C(7,2)' },
      { expr: 'P(5, 2)',           desc: 'Permutations P(5,2)' },
      { expr: 'P(8, 3)',           desc: 'Permutations P(8,3)' },
      { expr: 'fibonacci(10)',     desc: 'Fibonacci: find F(10)' },
      { expr: 'fibonacci(15)',     desc: 'Fibonacci: find F(15)' },
      { expr: '2^10 mod 7',        desc: 'Modular exponentiation' },
      { expr: '17 mod 5',          desc: 'Basic modular arithmetic' },
    ],
  },

  physics: {
    id: 'physics',
    label: 'Physics',
    supportedActions: [
      "Ohm\u2019s Law (V = IR)",
      'Kinetic Energy (KE = \u00bd mv\u00b2)',
      'Potential Energy (PE = mgh)',
      'Projectile Range',
      'Wave Speed (v = f\u03bb)',
      "Newton\u2019s 2nd Law (F = ma)",
      'Momentum (p = mv)',
      "Hooke\u2019s Law (F = kx)",
      'Power (P = W/t)',
      'Pressure (P = F/A)',
    ],
    practicePrompt: 'Create physics formula practice covering at least mechanics and electricity with substitution steps, unit tracking, and one applied scenario question.',
    examples: [
      { expr: 'ohm V=12 I=3',           desc: "Ohm\u2019s Law \u2014 find resistance R" },
      { expr: 'ohm V=9 R=3',            desc: "Ohm\u2019s Law \u2014 find current I" },
      { expr: 'KE m=10 v=5',            desc: 'Kinetic energy (KE = \u00bdmv\u00b2)' },
      { expr: 'KE m=2 v=10',            desc: 'KE with different values' },
      { expr: 'PE m=10 h=5',            desc: 'Gravitational potential energy' },
      { expr: 'PE m=5 h=20',            desc: 'PE at height 20 m' },
      { expr: 'projectile v=50 theta=45', desc: 'Projectile range at 45\u00b0' },
      { expr: 'projectile v=30 theta=30', desc: 'Projectile range at 30\u00b0' },
      { expr: 'wave f=440 lambda=0.78', desc: 'Wave speed (v = f\u03bb)' },
      { expr: 'wave f=200 lambda=1.5',  desc: 'Wave speed with different values' },
      { expr: 'force m=5 a=3',          desc: "Newton\u2019s 2nd Law (F = ma)" },
      { expr: 'force m=12 a=9.8',       desc: 'Weight force under gravity' },
    ],
  },
};

export const MATH_SYMBOL_GROUPS: Array<{
  id: 'basic' | 'algebra' | 'calculus' | 'trigonometry' | 'matrices' | 'vectors' | 'greek';
  label: string;
  symbols: Array<{ label: string; insert: string }>;
}> = [
  {
    id: 'basic',
    label: 'Basic',
    symbols: [
      { label: 'x\u00b2',  insert: '^2' },
      { label: 'x\u02b8',  insert: '^()' },
      { label: '\u221a',   insert: 'sqrt()' },
      { label: '|x|',     insert: 'abs()' },
      { label: '\u03c0',   insert: 'pi' },
      { label: '\u221e',   insert: 'inf' },
      { label: '\u00f7',   insert: '/' },
      { label: '\u00d7',   insert: '*' },
    ],
  },
  {
    id: 'algebra',
    label: 'Algebra',
    symbols: [
      { label: '=',          insert: ' = ' },
      { label: '\u2264',     insert: ' <= ' },
      { label: '\u2265',     insert: ' >= ' },
      { label: '\u2260',     insert: ' != ' },
      { label: '( )',        insert: '()' },
      { label: '[ ]',        insert: '[]' },
      { label: 'factor',     insert: 'factor ' },
      { label: 'simplify',   insert: 'simplify ' },
      { label: 'log',        insert: 'log()' },
      { label: 'log\u2082',  insert: 'log2()' },
    ],
  },
  {
    id: 'calculus',
    label: 'Calculus',
    symbols: [
      { label: 'd/dx',       insert: 'derivative of ()' },
      { label: 'd\u00b2/dx\u00b2', insert: 'derivative of derivative of ()' },
      { label: '\u222b',     insert: 'integral of () dx' },
      { label: '\u222b\u2090\u1d47', insert: 'integral from a to b of () dx' },
      { label: 'lim',        insert: 'limit x->0 of ()' },
      { label: 'lim \u221e', insert: 'limit x->inf of ()' },
      { label: 'sin',        insert: 'sin()' },
      { label: 'cos',        insert: 'cos()' },
      { label: 'tan',        insert: 'tan()' },
      { label: 'ln',         insert: 'log()' },
      { label: 'e\u02e3',    insert: 'e^()' },
    ],
  },
  {
    id: 'trigonometry',
    label: 'Trigonometry',
    symbols: [
      { label: 'sin',        insert: 'sin()' },
      { label: 'cos',        insert: 'cos()' },
      { label: 'tan',        insert: 'tan()' },
      { label: 'asin',       insert: 'asin()' },
      { label: 'acos',       insert: 'acos()' },
      { label: 'atan',       insert: 'atan()' },
      { label: 'sin\u00b2+cos\u00b2', insert: 'sin()^2 + cos()^2' },
      { label: '\u03c0/6',   insert: 'pi/6' },
      { label: '\u03c0/4',   insert: 'pi/4' },
      { label: '\u03c0/3',   insert: 'pi/3' },
      { label: '\u03c0/2',   insert: 'pi/2' },
      { label: '\u03b8',     insert: 'theta' },
    ],
  },
  {
    id: 'matrices',
    label: 'Matrices',
    symbols: [
      { label: '[[]]',   insert: '[[1,2],[3,4]]' },
      { label: 'det',    insert: 'det()' },
      { label: 'inv',    insert: 'inv()' },
      { label: 'A\u00b7B', insert: '[[1,2],[3,4]] * [[5,6],[7,8]]' },
      { label: '3\u00d73', insert: '[[1,2,3],[4,5,6],[7,8,9]]' },
    ],
  },
  {
    id: 'vectors',
    label: 'Vectors',
    symbols: [
      { label: '\u27e8v\u27e9',  insert: '[3,4]' },
      { label: '3D',            insert: '[1,2,3]' },
      { label: 'u\u00b7v',      insert: 'dot product [3,2] [1,4]' },
      { label: '|v|',           insert: 'magnitude [3,4]' },
      { label: '\u03b8',        insert: 'angle between [a,b] [c,d]' },
    ],
  },
  {
    id: 'greek',
    label: 'Greek',
    symbols: [
      { label: '\u03b1', insert: 'alpha' },
      { label: '\u03b2', insert: 'beta' },
      { label: '\u03b3', insert: 'gamma' },
      { label: '\u03b8', insert: 'theta' },
      { label: '\u03bb', insert: 'lambda' },
      { label: '\u03bc', insert: 'mu' },
      { label: '\u03c3', insert: 'sigma' },
      { label: '\u03c6', insert: 'phi' },
      { label: '\u03c9', insert: 'omega' },
    ],
  },
];
