/**
 * lib/export/pptx.ts
 *
 * Converts a report/essay into a PowerPoint presentation using pptxgenjs.
 * Each section of the report becomes one slide.
 * Slide 1 is always a title slide.
 */

// pptxgenjs is a client-side only library — never import at top level on the server.
// Callers must only call this from browser code.

interface ReportSlide {
  heading: string;
  bullets: string[];
}

// ── Section parser ────────────────────────────────────────────────────────────

function isHeadingLine(line: string, prevBlank: boolean, nextBlank: boolean): boolean {
  const trimmed = line.trim();
  if (!trimmed || trimmed.length > 100) return false;
  const noStop    = !trimmed.endsWith('.');
  const allCaps   = trimmed === trimmed.toUpperCase() && /[A-Z]{2}/.test(trimmed);
  const numbered  = /^\d+[\.\)]\s/.test(trimmed);
  return noStop && (allCaps || numbered || (prevBlank && nextBlank && trimmed.length <= 70));
}

/**
 * Split report text into slides. Each heading starts a new slide.
 * Body text under a heading becomes bullets (one per sentence, max 6 per slide).
 */
function parseReportToSlides(content: string, title: string): ReportSlide[] {
  const lines  = content.split('\n');
  const slides: ReportSlide[] = [];
  let currentHeading = title;
  let currentBullets: string[] = [];

  function flushSlide() {
    if (currentBullets.length > 0 || currentHeading !== title) {
      slides.push({ heading: currentHeading, bullets: currentBullets.slice(0, 6) });
    }
    currentBullets = [];
  }

  for (let i = 0; i < lines.length; i++) {
    const line     = lines[i];
    const trimmed  = line.trim();
    if (!trimmed) continue;

    const prevBlank = i === 0 || !lines[i - 1]?.trim();
    const nextBlank = i === lines.length - 1 || !lines[i + 1]?.trim();

    if (isHeadingLine(trimmed, prevBlank, nextBlank)) {
      flushSlide();
      currentHeading = trimmed
        .replace(/^\d+[\.\)]\s*/, '')          // strip leading "1. "
        .replace(/^[A-Z\s]+$/, t => t.trim()); // keep all-caps headings as-is
    } else {
      // Split long paragraphs into sentences and pick up to 3
      const sentences = trimmed
        .split(/(?<=[.!?])\s+/)
        .map(s => s.trim())
        .filter(s => s.length > 10)
        .slice(0, 3);
      currentBullets.push(...sentences);
    }
  }

  flushSlide();
  return slides;
}

// ── Colour palette ────────────────────────────────────────────────────────────

const THEME = {
  titleBg:    '1E3A5F',
  titleText:  'FFFFFF',
  slideBg:    'F8FAFC',
  accent:     '6366F1',
  headingText:'1E293B',
  bodyText:   '475569',
  bullet:     '6366F1',
} as const;

// ── Public API ────────────────────────────────────────────────────────────────

export interface PptxOptions {
  title:       string;
  subtitle?:   string;
  content:     string;
  references?: string[];
}

export async function generatePptx({ title, subtitle, content, references = [] }: PptxOptions): Promise<Blob> {
  // Dynamic import keeps this off the server bundle
  const PptxGenJS = (await import('pptxgenjs')).default;
  const prs = new PptxGenJS();

  prs.layout  = 'LAYOUT_WIDE'; // 16:9
  prs.author  = 'Scholar Hub';
  prs.subject = title;
  prs.title   = title;

  // ── Slide 1: Title slide ──────────────────────────────────────────────────
  const titleSlide = prs.addSlide();
  titleSlide.background = { color: THEME.titleBg };
  titleSlide.addText(title, {
    x: 0.5, y: 2.5, w: '90%', h: 1.5,
    fontSize: 36, bold: true, color: THEME.titleText,
    align: 'center', wrap: true,
  });
  if (subtitle) {
    titleSlide.addText(subtitle, {
      x: 0.5, y: 4.2, w: '90%', h: 0.6,
      fontSize: 18, color: 'A5B4FC',
      align: 'center', italic: true, wrap: true,
    });
  }
  titleSlide.addText('Generated by Scholar Hub', {
    x: 0.5, y: 5.5, w: '90%', h: 0.4,
    fontSize: 11, color: '94A3B8', align: 'center',
  });

  // ── Content slides ────────────────────────────────────────────────────────
  const contentSlides = parseReportToSlides(content, title);

  for (const slide of contentSlides) {
    const s = prs.addSlide();
    s.background = { color: THEME.slideBg };

    // Accent bar on left
    s.addShape(prs.ShapeType.rect, {
      x: 0, y: 0, w: 0.08, h: '100%',
      fill: { color: THEME.accent },
      line: { color: THEME.accent, width: 0 },
    });

    // Heading
    s.addText(slide.heading, {
      x: 0.35, y: 0.35, w: '92%', h: 0.75,
      fontSize: 22, bold: true, color: THEME.headingText, wrap: true,
    });

    // Divider
    s.addShape(prs.ShapeType.line, {
      x: 0.35, y: 1.1, w: '90%', h: 0,
      line: { color: 'E2E8F0', width: 1 },
    });

    // Bullet points
    if (slide.bullets.length > 0) {
      const bulletItems = slide.bullets.map(b => ({
        text: b,
        options: { bullet: { type: 'bullet' as const, indent: 15 }, color: THEME.bodyText },
      }));

      s.addText(bulletItems, {
        x: 0.45, y: 1.25, w: '88%', h: 3.8,
        fontSize: 16, color: THEME.bodyText,
        valign: 'top', wrap: true, lineSpacingMultiple: 1.4,
      });
    }

    // Slide number (bottom right)
    s.addText('Scholar Hub', {
      x: 8.5, y: 5.45, w: 1.5, h: 0.3,
      fontSize: 9, color: 'CBD5E1', align: 'right',
    });
  }

  // ── References slide (if any) ─────────────────────────────────────────────
  if (references.length > 0) {
    const refSlide = prs.addSlide();
    refSlide.background = { color: THEME.slideBg };

    refSlide.addShape(prs.ShapeType.rect, {
      x: 0, y: 0, w: 0.08, h: '100%',
      fill: { color: THEME.accent },
      line: { color: THEME.accent, width: 0 },
    });

    refSlide.addText('References', {
      x: 0.35, y: 0.35, w: '92%', h: 0.75,
      fontSize: 22, bold: true, color: THEME.headingText,
    });

    refSlide.addShape(prs.ShapeType.line, {
      x: 0.35, y: 1.1, w: '90%', h: 0,
      line: { color: 'E2E8F0', width: 1 },
    });

    const refItems = references.slice(0, 8).map((ref, i) => ({
      text: `[${i + 1}] ${ref}`,
      options: { color: THEME.bodyText, bullet: false },
    }));

    refSlide.addText(refItems, {
      x: 0.45, y: 1.3, w: '88%', h: 3.8,
      fontSize: 11, color: THEME.bodyText,
      valign: 'top', wrap: true, lineSpacingMultiple: 1.6,
    });
  }

  const blob = (await prs.write({ outputType: 'blob' })) as Blob;
  return blob;
}
